server:
  port: 8087
  servlet:
    context-path: /product

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/identity_service?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate # validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


  redis:
    host: localhost
    port: 6379
    timeout: 6000ms


app:
  services:
    oto: http://localhost:8080/identity
    file: http://localhost:8084
    profile: http://localhost:8081
    category: http://localhost:8086
    python: